restro1/urls.py
from django.contrib import admin
from django.urls import path,include
from customer.views import*
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('customer/',include('customer.urls')),
    path('management/',include('management.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404='customer.views.error_404_view'

management/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)


    def __str__(self):
       return self.name


class Dish(models.Model):
    cat=models.ForeignKey(Category,on_delete=models.CASCADE)

    title=models.CharField(max_length=100,blank=True,null=True)
    price=models.IntegerField(blank=True,null=True)
    mrp=models.IntegerField(blank=True,null=True)
    img1=models.FileField(blank=True,null=True)
    img2=models.FileField(blank=True,null=True)
    img3=models.FileField(blank=True,null=True)
    dis=models.TextField(blank=True,null=True)
    avail=models.BooleanField(blank=True,null=True,default=True)


    def __str__(self):
        return self.title+ '-----'+ str(self.cat.name)


class Team(models.Model):
    name=models.CharField(max_length=100,blank=True,null=True)
    designation=models.CharField(max_length=100,blank=True,null=True)
    img=models.FileField(blank=True,null=True)
    fb=models.URLField(blank=True,null=True)
    tu=models.URLField(blank=True,null=True)
    insta=models.URLField(blank=True,null=True)

    def __str__(self):
        return self.name

templates/about.html
{% extends 'base.html' %}
{% block body %}
{% load static %}



<section class="page_header">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<h2 class="text-uppercase wow fadeInDown">About us</h2>
<p class="wow fadeInUp">Read our Story, How we started and about the Team</p>
</div>
</div>
</div>
</section>

<section class="about2">
<div class="container">
<div class="row wow fadeInUp">
<div class="col-md-5">
<img src="{% static 'img/about.png' %}" class="img-responsive" alt="" />
</div>
<div class="col-md-7 text-left">
<h2 class="text-left">Our Story</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passage</p>
<a class="btn btn-default" role="button" href="#menu">See Our Menu</a>
</div>
</div>
</div>
</section>

<section class="services">
<div class="container">
<div class="row">
<div class="col-md-12">
<div class="page-header wow fadeInDown">
<h1 class="white">Special Service<small>What Special services we are offering now</small></h1>
</div>
</div>
</div>
<div class="row">
<div class="col-md-12">
<div class="services-slider wow fadeIn">
<div class="service-content text-center">
<img src="{% static 'img/ico1.png' %}" class="center-block" alt="" />
<h4 class="text-uppercase">Birthday Party</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
</div>
<div class="service-content text-center">
<img src="{% static 'img/ico2.png' %}" class="center-block" alt="" />
<h4 class="text-uppercase">Wedding Party</h4>
<p>Lorem Ipsum is simply dummy text of the printing. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>
</div>
<div class="service-content text-center">
<img src="{% static 'img/ico1.png' %}" class="center-block" alt="" />
<h4 class="text-uppercase">Birthday Party</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text ever since the 1500s, when an unknown printer.</p>
</div>
<div class="service-content text-center">
<img src="{% static 'img/ico2.png' %}" class="center-block" alt="" />
<h4 class="text-uppercase">Wedding Party</h4>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text when an unknown printer.</p>
</div>
</div>
</div>
</div>
</div>
</section>

<section class="team">
<div class="container">
<div class="row">
<div class="col-md-12">
<div class="page-header wow fadeInDown">
<h1>Our Team<small>The Hardworking Team behind the restaurant</small></h1>
</div>
</div>
</div>
 <div class="row">
  {% for i in team %}
<div class="col-md-3 col-sm-6 text-center">
<div class="team-staff wow fadeInUp" data-wow-delay="0.8s">
<img src="{{ i.img.url }}" style="display:flex;object-fit:cover;height:318px; width:260px; border-radius:120px 20px 120px 20px" class="img-responsive center-block" alt="" />
<h4>{{ i.name }}</h4>
<p>{{ i.designation }}</p>
<ul class="team-social">
<li><a href="{{ i.fb }}"><i class="fa fa-facebook"></i></a></li>
<li><a href="{{ i.tu }}"><i class="fa fa-twitter"></i></a></li>
<li><a href="{{ i.insta }}"><i class="fa fa-instagram"></i></a></li>
</ul>
</div>
</div>
  {% endfor %}
</div>
</div>
</section>
<div class="trusted">

<div class="trusted-quote">
<div class="container">
<div class="row">
<div class="col-md-offset-1 col-md-10 wow fadeIn">
<div class="trusted-slider">
<ul class="slides">
<li>
<img src="{% static 'img/quote.png' %}" alt="quote">
<p class="quote-body">The world’s a big, big stage for this notorious deli smack in the middle of the theatre district, infamously famous for its over-the-top corned beef and pastrami sandwiches, chopped liver, blintzes, celebrities, salami, smoked fish and New York’s finest cheesecake.</p>
<p class="quote-author">Anthony Reed, <span>New York</span></p>
</li>
<li>
<img src="{% static 'img/quote.png' %}" alt="quote">
<p class="quote-body">You might not find dragon meat on the menu, but you’ll find pretty much anything else that walks, swims or flies, cooked up in more ways than there are people in the Guangdong province. This Midtown mainstay has a 20-year history of delivering mouth-watering and Cantonese style chow.</p>
<p class="quote-author">Gemma Arterton, <span>Bay Area</span></p>
</li>
<li>
<img src="{% static 'img/quote.png' %}" alt="quote">
<p class="quote-body">This NYC historical landmark in the heart of the Theatre District has been serving up suds and down home pub food since 1892, surviving prohibition by renting the front of its then Rockefeller Center façade to Greek florists, while the Hurley brothers ran a speak-easy in back.</p>
 <p class="quote-author">Zachary Burton, <span>Sanfransisco</span></p>
</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>

<section class="menu space60" id="menu">
<div class="container">
<div class="row">
<div class="col-md-12">
<div class="page-header wow fadeInDown">
<h1>Our menu<small>These fine folks trusted the award winning restaurant.</small></h1>
</div>
</div>
</div>
<div class="food-menu wow fadeInUp">
<div class="row">
<div class="col-md-12">
<div class="menu-tags">
<span data-filter="*" class="tagsort-active">All</span>
<span data-filter=".starter">starters</span>
<span data-filter=".breakfast">breakfast</span>
<span data-filter=".lunch">lunch</span>
<span data-filter=".dinner">dinner</span>
<span data-filter=".desserts">desserts</span>
</div>
</div>
</div>
<div class="row menu-items">
<div class="menu-item col-sm-6 col-xs-12 starter dinner desserts">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 starter">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 breakfast desserts starter">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 breakfast">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 lunch starter breakfast featured">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
 </div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 lunch">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 dinner breakfast lunch">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 dinner">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 desserts lunch dinner">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
<div class="menu-item col-sm-6 col-xs-12 desserts">
<div class="clearfix menu-wrapper">
<h4>English asparagus</h4>
<span class="price">$14.95</span>
<div class="dotted-bg"></div>
</div>
<p>pellentesque enim. Aliquam tempor</p>
</div>
</div>
<div class="row">
<div class="col-md-12">
<div class="menu-btn">
<a class="btn btn-default btn-lg" href="menu_all.html" role="button">Explore our menu</a>
</div>
</div>
</div>
</div>
</div>
</section>

{% endblock body %}

templates/account.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

            <section class="page_header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <h2 class="text-uppercase">Account</h2>
                            <p>Please login or signup to continue with your purchase</p>
                        </div>
                    </div>
                </div>
            </section>

            <section class="shop-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row shop-login">
                                <div class="col-md-6">
                                    <div class="box-content">
                                        <h3 class="text-center">Existing Customer</h3>
                                        <br>
                                        <form method='post' class="logregform">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="form-group">
                                                    <div class="col-md-12">
                                                        <label>Username</label>
                                                        <input type="text" name='un' value="" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="row">
                                                <div class="form-group">
                                                    <div class="col-md-12">
                                                        <a class="pull-right" href="index-2.html">(Lost Password?)</a>
                                                        <label>Password</label>
                                                        <input type="password" name='pwd' value="" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <span class="remember-box checkbox">
                                                         {% if errorL %}
                                                            <p>Wrong username or password </p>
                                                         {% endif %}
                                                    </span>
                                                </div>
                                                <div class="col-md-6">
                                                    <button type="submit" name='login'
                                                        class="btn btn-default pull-right">Login</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="box-content">
                                        <h3 class="text-center">Register An Account</h3>
                                        <br>
                                        <form method='post' class="logregform">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="form-group">
                                                    <div class="col-md-12">
                                                        <label>E-mail Address</label>
                                                        <input type="email" name='e' value="" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                             <div class="row">
                                                <div class="form-group">
                                                    <div class="col-md-12">
                                                        <label>Username</label>
                                                        <input type="text" name='un' value="" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix space20"></div>
                                            <div class="row">
                                                <div class="form-group">
                                                    <div class="col-md-6">
                                                        <label>Password</label>
                                                        <input type="password" name='pwd1' value="" class="form-control">
                                                    </div>
                                                    <div class="col-md-6">
                                                        <label>Re-enter Password</label>
                                                        <input type="password" name='pwd2' value=""  class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            {% if errorPass %}
                                              <span><p>Password does't match </p></span>
                                            {% endif %}

                                            {% if errorUser %}
                                               <span><p>Username already taken </p></span>
                                            {% endif %}
                                            {% if errorEmail %}
                                             <span><p>Invalid Email </p></span>
                                            {% endif %}
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="space20"></div>
                                                    <button type="submit" name='signup'
                                                        class="btn btn-default pull-right">Register</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

{% endblock body %}

templates/contact.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

<section class="page_header">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<h2 class="text-uppercase">Contact</h2>
<p>Tomato is a delicious restaurant website template</p>
</div>
</div>
</div>
</section>

<section class="main-content contact-content">
<div class="container">
<div class="col-md-10 col-md-offset-1">
<div class="row">
<div class="col-md-6">
<h3 class="text-left no-margin-top">Address</h3>
<div class="footer-address contact-info">
<p><i class="fa fa-map-marker"></i>28 Seventh Avenue, Neew York, 10014</p>
<p><i class="fa fa-phone"></i>Phone: (415) 124-5678</p>
<p><i class="fa fa-envelope-o"></i><a href="https://demo.web3canvas.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="80f3f5f0f0eff2f4c0f2e5f3f4e1f5f2e1eef4aee3efed">[email&#160;protected]</a></p>
</div>
<br>
<h3 class="text-left no-margin-top">Working hours</h3>
<div class="contact-info text-muted">
<p>10:00 am to 11:00 pm on Weekdays</p>
<p>11:00 am to 11:30 pm on Weekends</p>
</div>
<br>
<h3 class="text-left no-margin-top">Follow Us</h3>
<div class="contact-social">
<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
<a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
<a href="https://www.dribbble.com/"><i class="fa fa-dribbble"></i></a>
<a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
</div>
</div>
<div class="col-md-6">
<form class="contact-form" id="contactForm" action="https://demo.web3canvas.com/themeforest/tomato/php/contact.php" method="post">
<div class="form-group">
<input class="form-control" name="name" id="name" placeholder="Full Name" type="text" required="required" />
</div>
<div class="form-group">
<input class="form-control" type="email" name="email" id="email" placeholder="Email Address" required="required" />
</div>
<div class="form-group">
<input class="form-control" placeholder="Subject" type="text" id="subject" name="subject">
</div>
<div class="form-group">
<textarea class="form-control" name="message" id="message" placeholder="Message" rows="5"></textarea>
</div>
<button class="btn btn-default btn-lg btn-block" id="js-contact-btn">Send message</button>
</form>
<div id="js-contact-result" data-success-msg="Form submitted successfully." data-error-msg="Oops. Something went wrong."></div>
</div>
</div>
</div>
</div>
</section>


<div id="map" data-latitude="40.6700" data-longitude="-73.9400"></div>

{% endblock body %}

templates/editcat.html
{% extends 'base2.html' %}
{% load static %}
{% block body %}
<div class="col-md-6">
                            <div class="page-header">
                                <h2>Categories</h2>
                            </div>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Dish</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in cat %}
                                    <tr>
                                        <td>{{i.name}}</td>
                                        <td>{{ i.dish_set.count }}</td>
                                        <td>
                                        <form action=""method="post">
                                            {% csrf_token %}
                                            <button type="submit" name="delete" value="{{ i.id }}" class="btn btn-danger">Delete</button>
                                         </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
</div>

                    <div class="col-md-6">
                            <div class="page-header">
                                <h2>Add Category</h2>
                            </div>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Enter Category Name</label>
                                    <input type="text" name='name' class="form-control" id="exampleInputEmail1" placeholder="Category">
                                </div>
                                <button type="submit" name="addcat" class="btn btn-default">Submit</button>
                            </form>
                    </div>
{% endblock %}

templates/editdish.html
{% extends 'base2.html' %}
{% load static %}
{% block body %}
<div class="col-md-6">
                            <div class="page-header">
                                <h2>DISHES</h2>
                            </div>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Availability</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in dish %}
                                    <tr>
                                        <td>{{i.title}}</td>
                                        <td>{{i.price}}</td>
                                        {% if i.avail %}
                                        <td>Available</td>
                                        {% else %}
                                        <td>Not Availble</td>
                                         {% endif %}
                                        <td>
                                        <form action=""method="post">
                                            {% csrf_token %}
                                            {% if i.avail %}
                                            <button type="submit" name='unavail' value="{{ i.id }}" class="btn btn-default">Unavailable</button>
                                            {% else %}
                                            <button type="submit" name='avail' value="{{ i.id }}" class="btn btn-success">Available</button>
                                            {% endif %}
                                            <button type="submit" name="delete" value="{{ i.id }}" class="btn btn-danger">Delete</button>
                                         </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>

                            </table>
                        </div>

                        <div class="col-md-6">
                            <div class="page-header">
                                <h2>Add Dish</h2>
                            </div>
                            <form method='post' enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Select Cotegory</label>
                                    <select class="form-control" name="cat">
                                        <option selected disabled>Select Category</option>
                                        {% for i in cat %}
                                           <option value="{{ i.id }}">{{ i.name }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Title</label>
                                    <input type="text" name="title" class="form-control" id="exampleInputPassword1" placeholder="title">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Price</label>
                                    <input type="text" name="price" class="form-control" id="exampleInputPassword1" placeholder="Price">
                                </div>
                                 <div class="form-group">
                                    <label for="exampleInputPassword1">Mrp</label>
                                    <input type="text" name="mrp" class="form-control" id="exampleInputPassword1" placeholder="Mrp">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Image First</label>
                                    <input type="file" name="img1" id="exampleInputFile">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Image Second</label>
                                    <input type="file" name="img2" id="exampleInputFile">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Image Third</label>
                                    <input type="file" name="img3" id="exampleInputFile">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Discription</label>
                                    <textarea class="form-control" name='dis' rows="5" cols="15" placeholder="Enter discription"></textarea>
                                </div>
                                <button type="submit" name="adddish" class="btn btn-default">Submit</button>
                            </form>
                        </div>

{% endblock %}

templates/editteam.html
{% extends 'base2.html' %}
{% load static %}
{% block body %}
 <div class="col-md-6">
                            <div class="page-header">
                                <h2>Edit_Team</h2>
                            </div>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Designation</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in team %}
                                    <tr>
                                        <td>{{i.name}}</td>
                                        <td>{{i.designation}}</td>
                                        <td>
                                         <form action=""method="post">
                                            {% csrf_token %}
                                            <button type="submit" name="delete" value="{{ i.id }}" class="btn btn-danger">Delete</button>
                                         </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
 </div>

<div class="col-md-6">
                            <div class="page-header">
                                <h2>Add Team</h2>
                            </div>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name='name' class="form-control" id="exampleInputEmail1" placeholder="Name">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">designation</label>
                                    <input type="text" name='designation' class="form-control" id="exampleInputEmail1" placeholder="Designation">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Image</label>
                                    <input type="file" name="img" id="exampleInputFile">
                                </div>
                                 <div class="form-group">
                                    <label for="exampleInputUrl">facebook</label>
                                    <input type="url" name="fb" id="exampleInputFile">
                                </div>

                                 <div class="form-group">
                                    <label for="exampleInputUrl">instagram</label>
                                    <input type="url" name="insta" id="exampleInputFile">
                                </div>

                                 <div class="form-group">
                                    <label for="exampleInputUrl">twitter</label>
                                    <input type="url" name="tu" id="exampleInputFile">
                                </div>


                                <button type="submit" name="addteam" class="btn btn-default">Submit</button>
                            </form>
                    </div>

{% endblock %}